// Copyright 2024 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-font-image --input D:/qmk_firmware/keyboards/kiwikey/0.libraries/thintel50.png --output D:/qmk_firmware/keyboards/kiwikey/0.libraries/graphics/resources --no-ascii False --unicode-glyphs  --format mono4 --no-rle False`

#pragma once

#include <qp.h>

extern const uint32_t font_thintel50_length;
extern const uint8_t  font_thintel50[8202];
