// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input D:/qmk_firmware/keyboards/kiwikey/0.libraries/ico32_brightness.png --output D:/qmk_firmware/keyboards/kiwikey/0.libraries/graphics/resources/icons --format mono4 --no-rle False --no-deltas False`

#pragma once

#include <qp.h>

extern const uint32_t gfx_ico32_brightness_length;
extern const uint8_t  gfx_ico32_brightness[294];
