// Copyright 2023 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics -i pusheen_240px.gif -f pal16`

#pragma once

#include <qp.h>

extern const uint32_t gfx_pusheen_240px_length;
extern const uint8_t  gfx_pusheen_240px[13229];
