// Copyright 2026 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by the TTF -> QFF converter with arguments:
//    input          | Font16.c
//    format         | mono4
//    rle            | True

#pragma once

#include <qp.h>

extern const uint32_t font_font16_length;
extern const uint8_t  font_font16[2274];
