// Copyright 2026 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by the TTF -> QFF converter with arguments:
//    input          | Nanoplex.ttf
//    size           | 32
//    format         | mono4
//    ascii          | True
//    unicode_glyphs | 
//    rle            | False
//    anti_aliasing  | True

#pragma once

#include <qp.h>

extern const uint32_t font_nanoplex32_length;
extern const uint8_t  font_nanoplex32[5620];
