// Copyright 2026 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by the TTF -> QFF converter with arguments:
//    input          | thintel.ttf
//    size           | 35
//    format         | mono2
//    ascii          | True
//    unicode_glyphs | 
//    rle            | True
//    anti_aliasing  | False

#pragma once

#include <qp.h>

extern const uint32_t font_thintel35_length;
extern const uint8_t  font_thintel35[2422];
