/*
	This file is generated from converted_data.xlsx
	Original keycodes from qmk_firmware/quantum/keycodes.h
*/
#pragma once

//  X (  Keycode             , Hex   ,    Text String   )

#define KEYCODE_LIST \
    X (  KC_NO                                        , 0x0000,    " "     ) \
    X (  KC_TRANSPARENT                               , 0x0001,    " "     ) \
    X (  KC_A                                         , 0x0004,    "a"     ) \
    X (  KC_B                                         , 0x0005,    "b"     ) \
    X (  KC_C                                         , 0x0006,    "c"     ) \
    X (  KC_D                                         , 0x0007,    "d"     ) \
    X (  KC_E                                         , 0x0008,    "e"     ) \
    X (  KC_F                                         , 0x0009,    "f"     ) \
    X (  KC_G                                         , 0x000A,    "g"     ) \
    X (  KC_H                                         , 0x000B,    "h"     ) \
    X (  KC_I                                         , 0x000C,    "i"     ) \
    X (  KC_J                                         , 0x000D,    "j"     ) \
    X (  KC_K                                         , 0x000E,    "k"     ) \
    X (  KC_L                                         , 0x000F,    "l"     ) \
    X (  KC_M                                         , 0x0010,    "m"     ) \
    X (  KC_N                                         , 0x0011,    "n"     ) \
    X (  KC_O                                         , 0x0012,    "o"     ) \
    X (  KC_P                                         , 0x0013,    "p"     ) \
    X (  KC_Q                                         , 0x0014,    "q"     ) \
    X (  KC_R                                         , 0x0015,    "r"     ) \
    X (  KC_S                                         , 0x0016,    "s"     ) \
    X (  KC_T                                         , 0x0017,    "t"     ) \
    X (  KC_U                                         , 0x0018,    "u"     ) \
    X (  KC_V                                         , 0x0019,    "v"     ) \
    X (  KC_W                                         , 0x001A,    "w"     ) \
    X (  KC_X                                         , 0x001B,    "x"     ) \
    X (  KC_Y                                         , 0x001C,    "y"     ) \
    X (  KC_Z                                         , 0x001D,    "z"     ) \
    X (  KC_1                                         , 0x001E,    "1"     ) \
    X (  KC_2                                         , 0x001F,    "2"     ) \
    X (  KC_3                                         , 0x0020,    "3"     ) \
    X (  KC_4                                         , 0x0021,    "4"     ) \
    X (  KC_5                                         , 0x0022,    "5"     ) \
    X (  KC_6                                         , 0x0023,    "6"     ) \
    X (  KC_7                                         , 0x0024,    "7"     ) \
    X (  KC_8                                         , 0x0025,    "8"     ) \
    X (  KC_9                                         , 0x0026,    "9"     ) \
    X (  KC_0                                         , 0x0027,    "0"     ) \
    X (  KC_ENTER                                     , 0x0028,    "Ent"     ) \
    X (  KC_ESCAPE                                    , 0x0029,    "Esc"     ) \
    X (  KC_BACKSPACE                                 , 0x002A,    "BKSP"     ) \
    X (  KC_TAB                                       , 0x002B,    "Tab"     ) \
    X (  KC_SPACE                                     , 0x002C,    "_"     ) \
    X (  KC_MINUS                                     , 0x002D,    "-"     ) \
    X (  KC_EQUAL                                     , 0x002E,    "="     ) \
    X (  KC_F1                                        , 0x003A,    "F1"     ) \
    X (  KC_F2                                        , 0x003B,    "F2"     ) \
    X (  KC_F3                                        , 0x003C,    "F3"     ) \
    X (  KC_F4                                        , 0x003D,    "F4"     ) \
    X (  KC_F5                                        , 0x003E,    "F5"     ) \
    X (  KC_F6                                        , 0x003F,    "F6"     ) \
    X (  KC_F7                                        , 0x0040,    "F7"     ) \
    X (  KC_F8                                        , 0x0041,    "F8"     ) \
    X (  KC_F9                                        , 0x0042,    "F9"     ) \
    X (  KC_F10                                       , 0x0043,    "F10"     ) \
    X (  KC_F11                                       , 0x0044,    "F11"     ) \
    X (  KC_F12                                       , 0x0045,    "F12"     ) \
    X (  KC_NUM_LOCK                                  , 0x0053,    "Num"     ) \
    X (  KC_KP_SLASH                                  , 0x0054,    "/"     ) \
    X (  KC_KP_ASTERISK                               , 0x0055,    "*"     ) \
    X (  KC_KP_MINUS                                  , 0x0056,    "-"     ) \
    X (  KC_KP_PLUS                                   , 0x0057,    "+"     ) \
    X (  KC_KP_ENTER                                  , 0x0058,    "="     ) \
    X (  KC_KP_1                                      , 0x0059,    "1"     ) \
    X (  KC_KP_2                                      , 0x005A,    "2"     ) \
    X (  KC_KP_3                                      , 0x005B,    "3"     ) \
    X (  KC_KP_4                                      , 0x005C,    "4"     ) \
    X (  KC_KP_5                                      , 0x005D,    "5"     ) \
    X (  KC_KP_6                                      , 0x005E,    "6"     ) \
    X (  KC_KP_7                                      , 0x005F,    "7"     ) \
    X (  KC_KP_8                                      , 0x0060,    "8"     ) \
    X (  KC_KP_9                                      , 0x0061,    "9"     ) \
    X (  KC_KP_0                                      , 0x0062,    "0"     ) \
    X (  KC_KP_DOT                                    , 0x0063,    "."     ) \
    X (  KC_AUDIO_MUTE                                , 0x00A8,    "X"     ) \
    X (  KC_AUDIO_VOL_UP                              , 0x00A9,    "V+"     ) \
    X (  KC_AUDIO_VOL_DOWN                            , 0x00AA,    "V-"     ) \
    X (  KC_MEDIA_NEXT_TRACK                          , 0x00AB,    ">>"     ) \
    X (  KC_MEDIA_PREV_TRACK                          , 0x00AC,    "<<"     ) \
    X (  KC_MEDIA_STOP                                , 0x00AD,    "STP"     ) \
    X (  KC_MEDIA_PLAY_PAUSE                          , 0x00AE,    "P/P"     ) \
    X (  KC_MEDIA_SELECT                              , 0x00AF,    "PLR"     ) \
    X (  KC_CALCULATOR                                , 0x00B2,    "Cal"     ) \
    X (  KC_MY_COMPUTER                               , 0x00B3,    "Com"     ) \
    X (  KC_WWW_HOME                                  , 0x00B5,    "Web"     ) \
    X (  KC_WWW_BACK                                  , 0x00B6,    "<"     ) \
    X (  KC_WWW_FORWARD                               , 0x00B7,    ">"     ) \
    X (  KC_WWW_REFRESH                               , 0x00B9,    "F5"     ) \
    X (  QK_MOUSE_CURSOR_UP                           , 0x00CD,    "^"     ) \
    X (  QK_MOUSE_CURSOR_DOWN                         , 0x00CE,    "v"     ) \
    X (  QK_MOUSE_CURSOR_LEFT                         , 0x00CF,    "<"     ) \
    X (  QK_MOUSE_CURSOR_RIGHT                        , 0x00D0,    ">"     ) \
    X (  QK_MOUSE_BUTTON_1                            , 0x00D1,    "L"     ) \
    X (  QK_MOUSE_BUTTON_2                            , 0x00D2,    "R"     ) \
    X (  QK_MOUSE_BUTTON_6                            , 0x00D6,    "BT1"     ) \
    X (  QK_MOUSE_BUTTON_7                            , 0x00D7,    "BT2"     ) \
    X (  QK_MOUSE_BUTTON_8                            , 0x00D8,    "BT3"     ) \
    X (  QK_MOUSE_WHEEL_UP                            , 0x00D9,    "W^"     ) \
    X (  QK_MOUSE_WHEEL_DOWN                          , 0x00DA,    "Wv"     ) \
    X (  QK_MOUSE_WHEEL_LEFT                          , 0x00DB,    "<W"     ) \
    X (  QK_MOUSE_WHEEL_RIGHT                         , 0x00DC,    "W>"     ) \
    X (  KC_LEFT_CTRL                                 , 0x00E0,    "Cmd"     ) \
    X (  KC_LEFT_SHIFT                                , 0x00E1,    "Shf"     ) \
    X (  KC_LEFT_ALT                                  , 0x00E2,    "Alt"     ) \
    X (  KC_LEFT_GUI                                  , 0x00E3,    "Win"     ) \
    X (  KC_RIGHT_CTRL                                , 0x00E4,    "Cmd"     ) \
    X (  KC_RIGHT_SHIFT                               , 0x00E5,    "Shf"     ) \
    X (  KC_RIGHT_ALT                                 , 0x00E6,    "Alt"     ) \
    X (  KC_RIGHT_GUI                                 , 0x00E7,    "Win"     ) \
    X (  QK_MACRO_0                                   , 0x7700,    "M0"     ) \
    X (  QK_MACRO_1                                   , 0x7701,    "M1"     ) \
    X (  QK_MACRO_2                                   , 0x7702,    "M2"     ) \
    X (  QK_MACRO_3                                   , 0x7703,    "M3"     ) \
    X (  QK_MACRO_4                                   , 0x7704,    "M4"     ) \
    X (  QK_MACRO_5                                   , 0x7705,    "M5"     ) \
    X (  QK_MACRO_6                                   , 0x7706,    "M6"     ) \
    X (  QK_MACRO_7                                   , 0x7707,    "M7"     ) \
    X (  QK_MACRO_8                                   , 0x7708,    "M8"     ) \
    X (  QK_MACRO_9                                   , 0x7709,    "M9"     ) \
    X (  QK_MACRO_10                                  , 0x770A,    "M10"     ) \
    X (  QK_MACRO_11                                  , 0x770B,    "M11"     ) \
    X (  QK_MACRO_12                                  , 0x770C,    "M12"     ) \
    X (  QK_MACRO_13                                  , 0x770D,    "M13"     ) \
    X (  QK_MACRO_14                                  , 0x770E,    "M14"     ) \
    X (  QK_MACRO_15                                  , 0x770F,    "M15"     ) \
    X (  QK_MACRO_16                                  , 0x7710,    "M16"     ) \
    X (  QK_MACRO_17                                  , 0x7711,    "M17"     ) \
    X (  QK_MACRO_18                                  , 0x7712,    "M18"     ) \
    X (  QK_MACRO_19                                  , 0x7713,    "M19"     ) \
    X (  QK_MACRO_20                                  , 0x7714,    "M20"     ) \
    X (  QK_MACRO_21                                  , 0x7715,    "M21"     ) \
    X (  QK_MACRO_22                                  , 0x7716,    "M22"     ) \
    X (  QK_MACRO_23                                  , 0x7717,    "M23"     ) \
    X (  QK_MACRO_24                                  , 0x7718,    "M24"     ) \
    X (  QK_MACRO_25                                  , 0x7719,    "M25"     ) \
    X (  QK_MACRO_26                                  , 0x771A,    "M26"     ) \
    X (  QK_MACRO_27                                  , 0x771B,    "M27"     ) \
    X (  QK_MACRO_28                                  , 0x771C,    "M28"     ) \
    X (  QK_MACRO_29                                  , 0x771D,    "M29"     ) \
    X (  QK_MACRO_30                                  , 0x771E,    "M30"     ) \
    X (  QK_MACRO_31                                  , 0x771F,    "M31"     ) \
    X (  QK_RGB_MATRIX_TOGGLE                         , 0x7842,    "RGB"     ) \
    X (  QK_RGB_MATRIX_MODE_NEXT                      , 0x7843,    "Ef>"     ) \
    X (  QK_RGB_MATRIX_MODE_PREVIOUS                  , 0x7844,    "<Ef"     ) \
    X (  QK_RGB_MATRIX_HUE_UP                         , 0x7845,    "C>"     ) \
    X (  QK_RGB_MATRIX_HUE_DOWN                       , 0x7846,    "<C"     ) \
    X (  QK_RGB_MATRIX_VALUE_UP                       , 0x7849,    "Br+"     ) \
    X (  QK_USER_0                                    , 0x7E40,    "#"     ) \
    X (  QK_USER_1                                    , 0x7E41,    "="     )
