// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input D:/qmk_firmware/keyboards/kiwikey/0_libraries/src_images/ico16_arrow_left.png --output D:/qmk_firmware/keyboards/kiwikey/0_libraries/src_images/../custom_display/qp/resources/icons --format mono2 --no-rle False --no-deltas False`

#pragma once

#include <qp.h>

extern const uint32_t gfx_ico16_arrow_left_length;
extern const uint8_t  gfx_ico16_arrow_left[64];
