// Copyright 2026 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `img2qgf` with arguments:
//    input  | Application.png
//    format | pal16

#pragma once

#include <qp.h>

extern const uint32_t gfx_ico22_gear_length;
extern const uint8_t  gfx_ico22_gear[343];
