#define EE_HANDS

#define BOOTMAGIC_ROW    0
#define BOOTMAGIC_COLUMN 0
#define BOOTMAGIC_ROW_RIGHT    5
#define BOOTMAGIC_COLUMN_RIGHT 0

#ifdef MOUSEKEY_ENABLE
	#define MOUSEKEY_INTERVAL 16
	#define MOUSEKEY_DELAY 0
	#define MOUSEKEY_TIME_TO_MAX 60
	#define MOUSEKEY_MAX_SPEED 7
	#define MOUSEKEY_WHEEL_DELAY 0
#endif
